[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "backtester_core"
requires-python = ">=3.12"
version = "0.1.0"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "backtester_core"
